DATA:
  BATCH_SIZE: 64
  IMG_SIZE: 224
  DATASET: coco_olac_cls
MODEL:
  TYPE: resnet
  NAME: resnet50
  DROP_RATE: 0.0
  NUM_CLASSES: 3
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-4
  BASE_LR: 2.81e-3
  WARMUP_LR: 2.81e-6
  MIN_LR: 2.81e-5
TEST:
  CROP: False
